language: emacs-lisp

env:
  matrix:
    - emacs=emacs-snapshot

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq $emacs

  # Install cask dependencies
  - curl -fsSLo /tmp/cask-master.zip https://github.com/cask/cask/archive/master.zip
  - sudo unzip -qq -d /opt /tmp/cask-master.zip
  - sudo ln -sf /opt/cask-master/bin/cask /usr/local/bin/cask
  - cask

script:
  - emacs --version
  - make test